Tale library: 2.6
MudLib:       Tale Demo, v1.3
Written by:   Irmen de Jong - irmen@razorvine.net
Driver start: Fri Jan  8 23:12:47 2016


Web server url:   http://127.0.0.1:8180/tale/

Critical Error. Shutting down.
Traceback (most recent call last):
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 205, in __startup_main_loop
    self.__main_loop_multiplayer()
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 664, in __main_loop_multiplayer
    pubsub.sync("driver-async-dialogs")
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/pubsub.py", line 58, in sync
    return all_topics[topic].sync()
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/pubsub.py", line 127, in sync
    results.extend(self.__sync_event(event))
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/pubsub.py", line 136, in __sync_event
    result = subber.pubsub_event(self.name, event)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 1049, in pubsub_event
    self.__continue_dialog(conn, dialog, None)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 419, in __continue_dialog
    why, what = dialog.send(message)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/cmds/normal.py", line 250, in do_put
    item.move(player, player)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/base.py", line 1013, in move
    target.insert(self, actor)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/base.py", line 818, in insert
    assert isinstance(item, Item)
AssertionError

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/main.py", line 28, in <module>
    Driver().start(sys.argv[1:])
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 81, in start
    self.__start(args)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 191, in __start
    self.__startup_main_loop(None)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 205, in __startup_main_loop
    self.__main_loop_multiplayer()
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 664, in __main_loop_multiplayer
    pubsub.sync("driver-async-dialogs")
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/pubsub.py", line 58, in sync
    return all_topics[topic].sync()
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/pubsub.py", line 127, in sync
    results.extend(self.__sync_event(event))
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/pubsub.py", line 136, in __sync_event
    result = subber.pubsub_event(self.name, event)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 1049, in pubsub_event
    self.__continue_dialog(conn, dialog, None)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/driver.py", line 419, in __continue_dialog
    why, what = dialog.send(message)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/cmds/normal.py", line 250, in do_put
    item.move(player, player)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/base.py", line 1013, in move
    target.insert(self, actor)
  File "/Volumes/Mac_data/Users/irmen/Projects/Tale/tale/base.py", line 818, in insert
    assert isinstance(item, Item)
AssertionError
